"""Codex app-server v2 protocol inventory for PlanningTree's session adapter.

This file is intentionally data-only. It documents the exact wire methods that
PlanningTree treats as canonical below ``threadId`` and gives tests a stable
place to assert that the adapter does not drift back to PlanningTree-only
semantics.
"""

from __future__ import annotations

SUPPORTED_CLIENT_METHODS: tuple[str, ...] = (
    "initialize",
    "thread/start",
    "thread/resume",
    "thread/fork",
    "thread/list",
    "thread/loaded/list",
    "thread/read",
    "thread/turns/list",
    "thread/unsubscribe",
    "thread/inject_items",
    "model/list",
    "skills/list",
    "turn/start",
    "turn/steer",
    "turn/interrupt",
    "config/batchWrite",
    "config/mcpServer/reload",
    "mcpServerStatus/list",
    "mcpServer/resource/read",
    "mcpServer/tool/call",
    "mcpServer/oauth/login",
)

EXPLICITLY_UNSUPPORTED_CLIENT_METHODS: tuple[str, ...] = (
    "thread/archive",
    "thread/unarchive",
    "thread/name/set",
    "thread/metadata/update",
    "thread/memoryMode/set",
    "thread/compact/start",
    "thread/rollback",
    "thread/shellCommand",
    "thread/backgroundTerminals/clean",
    "thread/increment_elicitation",
    "thread/decrement_elicitation",
    "thread/realtime/start",
    "thread/realtime/appendAudio",
    "thread/realtime/appendText",
    "thread/realtime/stop",
    "thread/realtime/listVoices",
    "review/start",
    "marketplace/add",
    "plugin/list",
    "plugin/read",
    "app/list",
    "fs/readFile",
    "fs/writeFile",
    "fs/createDirectory",
    "fs/getMetadata",
    "fs/readDirectory",
    "fs/remove",
    "fs/copy",
    "fs/watch",
    "fs/unwatch",
    "account/read",
    "account/login/start",
    "account/login/cancel",
    "account/logout",
    "account/rateLimits/read",
    "config/read",
    "config/value/write",
    "command/exec",
    "command/exec/write",
    "command/exec/terminate",
    "command/exec/resize",
)

SUPPORTED_SERVER_NOTIFICATIONS: tuple[str, ...] = (
    "error",
    "thread/started",
    "thread/status/changed",
    "thread/closed",
    "thread/tokenUsage/updated",
    "turn/started",
    "turn/completed",
    "item/started",
    "item/completed",
    "item/agentMessage/delta",
    "item/plan/delta",
    "item/commandExecution/outputDelta",
    "item/commandExecution/terminalInteraction",
    "item/fileChange/outputDelta",
    "serverRequest/created",
    "serverRequest/updated",
    "serverRequest/resolved",
    "warning",
)

UNSUPPORTED_SERVER_NOTIFICATIONS: tuple[str, ...] = (
    "thread/archived",
    "thread/unarchived",
    "skills/changed",
    "thread/name/updated",
    "hook/started",
    "hook/completed",
    "turn/diff/updated",
    "turn/plan/updated",
    "item/autoApprovalReview/started",
    "item/autoApprovalReview/completed",
    "rawResponseItem/completed",
    "command/exec/outputDelta",
    "item/mcpToolCall/progress",
    "mcpServer/oauthLogin/completed",
    "mcpServer/startupStatus/updated",
    "account/updated",
    "account/rateLimits/updated",
    "app/list/updated",
    "externalAgentConfig/import/completed",
    "fs/changed",
    "item/reasoning/summaryTextDelta",
    "item/reasoning/summaryPartAdded",
    "item/reasoning/textDelta",
    "thread/compacted",
    "model/rerouted",
    "deprecationNotice",
    "configWarning",
    "thread/realtime/started",
    "thread/realtime/itemAdded",
    "thread/realtime/transcript/delta",
    "thread/realtime/transcript/done",
    "thread/realtime/outputAudio/delta",
    "thread/realtime/sdp",
    "thread/realtime/error",
    "thread/realtime/closed",
)
